version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on 'date'
      - echo "AWS_DEFAULT_REGION is $AWS_DEFAULT_REGION"
      - echo "AWS_REGION" is $AWS_DEFAULT_REGION"
      - echo "DEBUG PARTITION is $PARTITION"

  post_build:
    commands:
      - bash -x buildmagic_createTrustedKeyGroup.sh "SKIP_LOGIN" #--# don't use -x to not output keys and secrets

  artifacts:
    files:
      - buildmagic_createTrustedKeyGroup.sh
