AWSTemplateFormatVersion: '2010-09-09'
Description: Simple Lambda function with API Gateway
Parameters:
  Environment:
    Type: String
    Description: Environment name (dev/qa/prod)
    Default: dev
  ProjectId:
    Type: String
    Description: Project identifier
    Default: userdetails
  S3bucket:
    Type: String
    Description: Existing S3 bucket name for Lambda code
    Default: ''
  DBSecrets:
    Type: String
    Description: Database master password
    Default: ''
  VpcId:
    Type: String
    Description: VPC ID where Aurora cluster exists
    Default: ''
  SubnetIds:
    Type: String
    Description: Comma-separated list of subnet IDs (at least 2)
    Default: ''
  SecurityGroupId:
    Type: String
    Description: Security Group ID of Aurora cluster (required if using VPC)
    Default: ''
Conditions:
  HasVpc:
    Fn::Not:
    - Fn::Equals:
      - Ref: VpcId
      - ''
  HasSg:
    Fn::Not:
    - Fn::Equals:
      - Ref: SecurityGroupId
      - ''
  HasVpcAndSg:
    Fn::And:
    - Condition: HasVpc
    - Condition: HasSg
  HasS3Bucket:
    Fn::Not:
    - Fn::Equals:
      - Ref: S3bucket
      - ''
  CreateS3Bucket:
    Fn::Equals:
    - Ref: S3bucket
    - ''
  CreateLambdaSg:
    Fn::And:
    - Condition: HasVpc
    - Fn::Not:
      - Condition: HasSg
  HasDBSecrets:
    Fn::Not:
    - Fn::Equals:
      - Ref: DBSecrets
      - ''
Resources:
  S3ConfigBucket:
    Type: AWS::S3::Bucket
    Condition: CreateS3Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName:
        Fn::Sub: ${ProjectId}-${Environment}-${AWS::AccountId}-bucket
      VersioningConfiguration:
        Status: Enabled
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - Fn::If:
        - HasVpc
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - Ref: AWS::NoValue
      Policies:
      - Fn::If:
        - HasDBSecrets
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - secretsmanager:GetSecretValue
              Resource:
                Ref: DBSecrets
        - Ref: AWS::NoValue
      - PolicyName: S3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            Resource:
              Fn::If:
              - HasS3Bucket
              - Fn::Sub: arn:aws:s3:::${S3bucket}/*
              - Fn::Sub: ${S3ConfigBucket.Arn}/*
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateLambdaSg
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId:
        Ref: VpcId
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
        Description: Allow all outbound traffic
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${ProjectId}-${Environment}-lambda-sg
  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Condition: HasVpc
    Properties:
      VpcId:
        Ref: VpcId
      ServiceName:
        Fn::Sub: com.amazonaws.${AWS::Region}.secretsmanager
      VpcEndpointType: Interface
      SubnetIds:
        Fn::Split:
        - ','
        - Ref: SubnetIds
      SecurityGroupIds:
      - Fn::If:
        - HasSg
        - Ref: SecurityGroupId
        - Ref: LambdaSecurityGroup
      PrivateDnsEnabled: true
  GetDataFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ProjectId}-${Environment}-lambda
      Handler: index.handler
      Runtime: nodejs20.x
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      MemorySize: 512
      Timeout: 30
      VpcConfig:
        Fn::If:
        - HasVpc
        - SecurityGroupIds:
          - Fn::If:
            - HasSg
            - Ref: SecurityGroupId
            - Ref: LambdaSecurityGroup
          SubnetIds:
            Fn::Split:
            - ','
            - Ref: SubnetIds
        - Ref: AWS::NoValue
      Environment:
        Variables:
          ENVIRONMENT:
            Ref: Environment
          PROJECT_ID:
            Ref: ProjectId
          DB_SECRET_ARN:
            Ref: DBSecrets
      Code:
        S3Bucket: userdetails-us-east-1-851725398530-pipeline-artifacts
        S3Key: c7bf16a1a3ed84e00e67b4381c763e3a
  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: GetDataFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/*
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name:
        Fn::Sub: ${ProjectId}-${Environment}-api
      Description: Simple API for Lambda function
  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: ApiGateway
      ParentId:
        Fn::GetAtt:
        - ApiGateway
        - RootResourceId
      PathPart: getRegion
  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:
        Ref: ApiGateway
      ResourceId:
        Ref: ApiResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDataFunction.Arn}/invocations
      MethodResponses:
      - StatusCode: 200
        ResponseParameters:
          method.response.header.Access-Control-Allow-Origin: true
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiMethod
    Properties:
      RestApiId:
        Ref: ApiGateway
      StageName:
        Ref: Environment
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/getRegion
    Export:
      Name:
        Fn::Sub: ${ProjectId}-${Environment}-api-url
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetDataFunction
      - Arn
    Export:
      Name:
        Fn::Sub: ${ProjectId}-${Environment}-lambda-arn
  LambdaFunctionName:
    Description: Lambda Function Name
    Value:
      Ref: GetDataFunction
    Export:
      Name:
        Fn::Sub: ${ProjectId}-${Environment}-lambda
  DatabaseSecretArn:
    Description: Secrets Manager secret ARN for database credentials
    Value:
      Ref: DBSecrets
    Export:
      Name:
        Fn::Sub: ${ProjectId}-${Environment}-db-secret-arn
  S3BucketName:
    Description: S3 Bucket for Lambda code
    Value:
      Fn::If:
      - HasS3Bucket
      - Ref: S3bucket
      - Ref: S3ConfigBucket
    Export:
      Name:
        Fn::Sub: ${ProjectId}-${Environment}-bucket
