AWSTemplateFormatVersion: '2010-09-09'
Description: Simple Lambda function with API Gateway

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev/qa/prod)
    Default: dev
  ProjectId:
    Type: String
    Description: Project identifier
    Default: userdetails
  DBSecrets:
    Type: String
    Description: Database master password
    Default: ''
  VpcId:
    Type: String
    Description: VPC ID where Aurora cluster exists
    Default: ''
  SubnetIds:
    Type: String
    Description: Comma-separated list of subnet IDs (at least 2)
    Default: ''
  SecurityGroupId:
    Type: String
    Description: Security Group ID of Aurora cluster (required if using VPC)
    Default: ''

Conditions:
  HasVpc: !Not [!Equals [!Ref VpcId, '']]
  HasSg: !Not [!Equals [!Ref SecurityGroupId, '']]
  HasVpcAndSg: !And
    - !Condition HasVpc
    - !Condition HasSg
  CreateLambdaSg: !And
    - !Condition HasVpc
    - !Not [!Condition HasSg]
  HasDBSecrets: !Not [!Equals [!Ref DBSecrets, '']]

Resources:
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !If [HasVpc, 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole', !Ref 'AWS::NoValue']

  SecretsManagerPolicy:
    Type: AWS::IAM::Policy
    Condition: HasDBSecrets
    Properties:
      PolicyName: SecretsManagerAccess
      Roles:
        - !Ref LambdaExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Ref DBSecrets

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateLambdaSg
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${ProjectId}-${Environment}-lambda-sg'
  
  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Condition: HasVpc
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      VpcEndpointType: Interface
      SubnetIds: !Split [',', !Ref SubnetIds]
      SecurityGroupIds:
        - !If [HasSg, !Ref SecurityGroupId, !Ref LambdaSecurityGroup]
      PrivateDnsEnabled: true

  GetDataFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectId}-${Environment}-lambda'
      Handler: index.handler
      Runtime: nodejs20.x
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 512
      Timeout: 30
      VpcConfig:
        !If
          - HasVpc
          - SecurityGroupIds:
              - !If [HasSg, !Ref SecurityGroupId, !Ref LambdaSecurityGroup]
            SubnetIds: !Split [',', !Ref SubnetIds]
          - !Ref AWS::NoValue
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          PROJECT_ID: !Ref ProjectId
          DB_SECRET_ARN: !Ref DBSecrets
      Code: ./lambdas_nodejs/getCounty

  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetDataFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/*'

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${ProjectId}-${Environment}-api'
      Description: Simple API for Lambda function

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: getRegion

  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDataFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref Environment

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/getRegion'
    Export:
      Name: !Sub '${ProjectId}-${Environment}-api-url'
  
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt GetDataFunction.Arn
    Export:
      Name: !Sub '${ProjectId}-${Environment}-lambda-arn'
  
  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref GetDataFunction
    Export:
      Name: !Sub '${ProjectId}-${Environment}-lambda'
  
  DatabaseSecretArn:
    Description: Secrets Manager secret ARN for database credentials
    Value: !Ref DBSecrets
    Export:
      Name: !Sub '${ProjectId}-${Environment}-db-secret-arn'
