
AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
Description: Simple Lambda function with API Gateway

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev/qa/prod)
    Default: dev
  ProjectId:
    Type: String
    Description: Project identifier
    Default: userdetails
  DBSecrets:
    Type: String
    Description: Database master password
    Default: ''
  VpcId:
    Type: String
    Description: VPC ID where Aurora cluster exists (optional)
    Default: ''
  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma-separated list of subnet IDs (at least 2, optional)
    Default: ''
  SecurityGroupIds:
    Type: CommaDelimitedList
    Description: Comma-separated list of Security Group IDs for Lambda (optional)
    Default: ''

  
  # ApiVpcEndpoints:
  #   Type: List<String>
  #   Description: Enter the VPC Endpoint IDs for private API Gateway (optional)
  #   Default: []

Conditions:
  HasVpcConfig: !Not [!Equals [!Ref VpcId, '']]

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 512
    Environment:  
      Variables:
        ENVIRONMENT: !Ref Environment
        PROJECT_ID: !Ref ProjectId
        DB_SECRET_ARN: !Ref DBSecrets

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors:
        AllowMethods: "'GET,HEAD,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,access-Control-Allow-Origin,Access-Control-Allow-Headers'"
        AllowOrigin: "'*'"
      EndpointConfiguration:
        Type: REGIONAL
      # To make it PRIVATE, uncomment below and provide ApiVpcEndpoints
      # EndpointConfiguration:
      #   Type: PRIVATE
      #   VPCEndpointIds: !Ref ApiVpcEndpoints

  GetDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectId}-${Environment}-lambda'
      Handler: index.handler
      CodeUri: ./lambdas_nodejs/getCounty
      VpcConfig: !If
        - HasVpcConfig
        - SubnetIds: !Ref SubnetIds
          SecurityGroupIds: !Ref SecurityGroupIds
        - !Ref AWS::NoValue
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetRegion:
          Type: Api
          Properties:
            Path: /{ProjectId}/{Environment}/region
            Method: get
            RestApiId: !Ref ApiGatewayApi
        GetRegionWithId:
          Type: Api
          Properties:
            Path: /{ProjectId}/{Environment}/region/{id}
            Method: get
            RestApiId: !Ref ApiGatewayApi
        GetLocalities:
          Type: Api
          Properties:
            Path: /{ProjectId}/{Environment}/locality
            Method: get
            RestApiId: !Ref ApiGatewayApi

  ApiGatewayUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ApiGatewayApiv1Stage
    Properties:
      UsagePlanName: !Sub "${ProjectId}-usage-plan"
      ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: v1
      Description: "Usage plan for API access with rate limiting"
      Quota:
        Limit: 10000
        Period: MONTH
      Throttle:
        BurstLimit: 100
        RateLimit: 50

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DBSecrets

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/v1/${ProjectId}/${Environment}/region'
    Export:
      Name: !Sub '${ProjectId}-${Environment}-api-url'
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt GetDataFunction.Arn
    Export:
      Name: !Sub '${ProjectId}-${Environment}-lambda-arn'
  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref GetDataFunction
    Export:
      Name: !Sub '${ProjectId}-${Environment}-lambda'
  DatabaseSecretArn:
    Description: Secrets Manager secret ARN for database credentials
    Value: !Ref DBSecrets
    Export:
      Name: !Sub '${ProjectId}-${Environment}-db-secret-arn'
